name: espo
description: A futuristic social media app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0  # Use the latest stable version
  firebase_auth: latest_version
  cloud_firestore: latest_version
  provider: latest_version
  image_picker: latest_version
  shared_preferences: latest_version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
